CREATE TABLE SALESMAN(
SID INTEGER PRIMARY KEY,
NAME VARCHAR(20),
CITY VARCHAR(20),
COMMISSION INTEGER
);
DROP TABLE SALESMAN;
INSERT INTO SALESMAN VALUES(1000,'RAJ','BENGALURU',50);
INSERT INTO SALESMAN VALUES(2000,'ASHWIN','TUMKUR',30);
INSERT INTO SALESMAN VALUES(3000,'BINDU','MUMBAI',40);
INSERT INTO SALESMAN VALUES(4000,'LAVANYA','BENGALURU',40);
INSERT INTO SALESMAN VALUES(5000,'ROHIT','MYSORE',60);

CREATE TABLE CUSTOMER(
CID INTEGER PRIMARY KEY,
CNAME VARCHAR(20),
CITY VARCHAR(20),
GRADE CHAR(1),
SID INTEGER,
FOREIGN KEY(SID) REFERENCES SALESMAN(SID) ON DELETE CASCADE
);
DROP TABLE CUSTOMER;
INSERT INTO CUSTOMER VALUES(11,'INFOSYS','BENGALURU',5,1000);
INSERT INTO CUSTOMER VALUES(22,'TCS','BENGALURU',4,2000);
INSERT INTO CUSTOMER VALUES(33,'WIPRO','MYSORE',7,1000);
INSERT INTO CUSTOMER VALUES(44,'TCS','MYSORE',6,2000);
INSERT INTO CUSTOMER VALUES(55,'ORACLE','TUMKUR',3,3000);

CREATE TABLE ORDERS(
ORD_NO INTEGER PRIMARY KEY,
P_AMT INTEGER,
ORD_DATE DATE,
CID INTEGER,
SID INTEGER,
FOREIGN KEY(CID) REFERENCES CUSTOMER(CID) ON DELETE CASCADE,
FOREIGN KEY(SID) REFERENCES SALESMAN(SID) ON DELETE CASCADE
);
DROP TABLE ORDERS;
INSERT INTO ORDERS VALUES(1,200000,'16-04-12',11,1000);
INSERT INTO ORDERS VALUES(2,300000,'16-04-12',11,2000);
INSERT INTO ORDERS VALUES(3,400000,'17-04-15',22,1000);

-- QUERY 1
SELECT COUNT(CID)
FROM CUSTOMER
WHERE GRADE>(
SELECT AVG(GRADE)
FROM CUSTOMER
WHERE CITY='BENGALURU'
);

-- QUERY 2
SELECT NAME,COUNT(CID)
FROM SALESMAN S,CUSTOMER C
WHERE S.SID=C.SID
GROUP BY NAME
HAVING COUNT(CID)>1; 

-- QUERY 3
(SELECT NAME
FROM SALESMAN S,CUSTOMER C
WHERE S.SID=C.SID AND S.CITY=C.CITY)
UNION
(SELECT NAME
FROM SALESMAN S
WHERE S.SID NOT IN(SELECT S.SID
				FROM SALESMAN S, CUSTOMER C
				WHERE S.SID=C.SID AND S.CITY=C.CITY)
);

-- QUERY 4
CREATE VIEW HIGHEST_ORD AS
SELECT SID,P_AMT
FROM ORDERS O
WHERE P_AMT=(SELECT MAX(P_AMT)
			FROM ORDERS
            WHERE ORD_DATE='16-04-12'
);

SELECT * FROM HIGHEST_ORD;

-- QUERY 5
DELETE FROM SALESMAN
WHERE SID=1000;

SET FOREIGN_KEY_CHECKS=1;

SELECT * FROM SALESMAN;
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;

